# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BeersApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Pods for BeersApp
  
  pod 'IQKeyboardManagerSwift'
  pod 'PKHUD', '~> 5.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'GoogleSignIn'
  pod 'SCLAlertView'
  pod 'UPCarouselFlowLayout'
  pod 'Alamofire', '~> 5.1'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'LGButton'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

end

target 'todayWidget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Pods for todayWidget
  
  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire', '~> 5.1'
  
end
